### ISSUE TITLE
[OOB 5.6] Example compiles for Odin, but no output

### ISSUE THREAD

**Issue by micgur01** [ARMmbed/mbed-os-example-wifi#59] opened 2017-09-18 12:51 UTC

**Comment by SeppoTakalo** [comment] 2017-09-18 14:04
This is duplicate of https://github.com/ARMmbed/mbed-os-example-wifi/issues/58

**Comment by SeppoTakalo** [comment] 2017-09-19 08:04
Closing this as a duplicate.

**Closed by SeppoTakalo** 2017-09-19 08:04 UTC
