### ISSUE TITLE
Running this on NUCLEO_L476RG + ST Wifi X-NUCLEO-IDW01A1 prints error _recv_ap (212) on serial port

### ISSUE THREAD

**Issue by GarySwansonARM** [ARMmbed/mbed-os-example-wifi#94] opened 2018-03-19 15:50 UTC
On windows.
mbed import mbed-os-example-wifi
mbed update mbed-os-5.8.0-oob
mbed compile -t IAR -m NUCLEO_L476RG
flash to board & reset
On the serial port I see:
Scan:
_recv_ap (212) - ERROR: Should never happen!
Network: Hidden-Network secured: WPA2 BSSID: F8:B:CB:43:46:80 RSSI: -83 Ch: 1
Network: AccessNG secured: WPA2 BSSID: 70:3A:E:64:4e:c0 RSSI: -84 Ch: 1
Network: TP-LINK_ACD326 secured: WPA2 BSSID: C4:E9:84:ac:d3:26 RSSI: -69 Ch: 3
Network: Guest-AccessNG secured: None BSSID: 70:3A:E:64:95:c1 RSSI: -57 Ch: 6
Network: ASUS secured: Unknown BSSID: 1C:B7:2C:7c:3d:c0 RSSI: -53 Ch: 6
5 networks available.

**Comment by GarySwansonARM** [comment] 2018-03-19 16:31
This happened for about 5 of the reboots, and has now not happened for the past 3.

**Comment by SeppoTakalo** [comment] 2018-03-20 09:48
Obviously a parser error in WiFi driver: https://github.com/ARMmbed/wifi-x-nucleo-idw01m1/blob/5871f7011d7ff2c50e3faf992ebab88e9f69dc95/SPWFSA01/SPWFSA01.cpp#L212

I cannot replicate that same with different board, new version of driver and IAR.

Can you try:
```
cd wifi-x-nucleo-idw01m1
git checkout master
git pull
cd ..
```
And recompile & retest.

The driver seems to be very old and probably needs updating.

**Comment by ciarmcom** [comment] 2018-05-31 15:54
ARM Internal Ref: ONME-3670

**Comment by SeppoTakalo** [comment] 2018-06-04 12:10
No updates, closing as the root cause was most probably outdated driver.

**Closed by SeppoTakalo** 2018-06-04 12:10 UTC
Labels: mirrored
